FROM amd64/ubuntu:16.04

RUN apt update && \
	apt install -y python3 python3-pip && \
	ln -s /usr/bin/python3 /usr/bin/python && \
	ln -s /usr/bin/pip3 /usr/bin/pip && \
	pip install numpy h5py pandas pymongo flask scikit-learn keras tensorflow argparse
